server:
  port: 3366

spring:
  application:
    name: config-client
  cloud:
    #    Config客户端配置
    config:
      label: master  #分支名称
      name: config  #配置文件名称
      profile: dev  #读取后缀名称
      #      综合上边的配置 路径就是: http://localhost:3344/master/config-dev.yml
      uri: http://localhost:3344  #配置中心地址

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
